### ISSUE TITLE
Using `servant-auth` with `hoistServer`

### ISSUE THREAD

**Issue by mschristiansen** [haskell-servant/servant-auth#108]
I have a reader monad for some config, which works fine until I include `Auth` in the API type. Then I get the following error

```
No instance for (HasContextEntry '[] Servant.Auth.Server.Internal.ConfigTypes.CookieSettings)
        arising from a use of `hoistServer'
```

```
type Foo = Auth '[Cookie] Text :> Get '[JSON] String

server :: App -> Server Foo
server app = hoistServer (Proxy :: Proxy Foo) (`runReaderT` app) foo

type AppHandler = ReaderT App Handler

foo :: AuthResult Text -> AppHandler String
foo _ = return "secret"

instance FromJWT Text
instance ToJWT Text
```
Am I just using it wrong or do I need to write an instance along the lines of
```
instance HasContextEntry (Context '[CookieSettings]) (AppHandler a)
```

**Comment by domenkozar** [comment]
You need http://hackage.haskell.org/package/servant-server-0.14.1/docs/Servant-Server.html#v:hoistServerWithContext

This clearly couls use some docs :)

**Comment by ibnuda** [comment]
Sorry for the shameless plug, but I'm writing a [blogpost](siskam.link/2018-07-02-thinkster-s-realworld---backend.html) implementing [realworld](https://github.com/gothinkster/realworld) in servant plus servant-auth which uses `hoistServer`.

**Comment by mschristiansen** [comment]
The solution to my problem above was in fact simple enough. `server` should just use `hoistServerWithContext` and receive a `Proxy :: Proxy '[CookieSettings, JWTSettings]`. Full definition of `server` below.

```
server :: App -> Server Foo
server app = hoistServerWithContext (Proxy :: Proxy Foo) context (runAppHandler app) foo
  where
    context :: Proxy '[CookieSettings, JWTSettings]
    context = Proxy
```
Thanks @domenkozar . Best place to add documentation? Maybe in [Servant.Auth](http://hackage.haskell.org/package/servant-auth-0.3.2.0/docs/Servant-Auth.html)? Doesn't quite belong with `hoistServerWithContext` documentation.

Thanks @ibnuda . Blogposts as solutions are certainly valid IMHO. I had it working similar to how you describe it, but that is basically unwrapping the authentication part before doing the "hoisting" and you loose ability to compose different servers.

**Comment by alpmestan** [comment]
Yes, `Servant.Auth`'s documentation sounds like a great place to say a few words about `hoistServerWithContext` and how to use it for servant-auth related purposes. Thanks @mschristiansen!

**Comment by mschristiansen** [comment]
The function below seems useful and with some documentation would go a long way towards using servant-auth with custom monad.

```
hoistServerWithAuth
  :: HasServer api '[CookieSettings, JWTSettings]
  => Proxy api
  -> (forall x. m x -> n x)
  -> ServerT api m
  -> ServerT api n
hoistServerWithAuth api nt =
  hoistServerWithContext api (Proxy :: Proxy '[CookieSettings, JWTSettings]) nt
```
PR?

**Comment by alpmestan** [comment]
Isn't it a little too specific? What if you add e.g basic auth, wouldn't that require a slightly different context?

**Comment by jkarni** [comment]
> Isn't it a little too specific? What if you add e.g basic auth, wouldn't
that require a slightly different context?

Or if you already have something in the context from some non-servant-auth
stuff.

**Comment by alpmestan** [comment]
Right, multipart would be an example. I made backend configuration happen through the context there as well.

**Comment by mschristiansen** [comment]
Closing now that #111 is merged
