### ISSUE TITLE
Really clear the cookies when clearing a session

### ISSUE THREAD

**Issue by adetokunbo** [haskell-servant/servant-auth#127]
clearSession does not clear the JWT and XSRF cookies; it sets their values to ' value'

That's because in https://github.com/haskell-servant/servant-auth/blob/a6e6040e8be28c1880ffc4e5d5be1d9954ba63e5/servant-auth-server/src/Servant/Auth/Server/Internal/Cookie.hs#L153 and in https://github.com/haskell-servant/servant-auth/blob/a6e6040e8be28c1880ffc4e5d5be1d9954ba63e5/servant-auth-server/src/Servant/Auth/Server/Internal/Cookie.hs#L155
it assumes that the Default (def) value of SetCookies is "", when in fact it is ["value"](https://www.stackage.org/haddock/lts-12.14/cookie-0.4.4/Web-Cookie.html#v:defaultSetCookie)

**Comment by 3noch** [comment]
This isn't technically *wrong* but it's not the best either. I.e. it assumes that `"value"` is not a valid session (which is about as safe an assumption as assuming that `""` is not a valid session). But it's not as intuitive to be sure.

**Comment by domenkozar** [comment]
@3noch any objections changing `clearSession` to set value as  `""`?
