### ISSUE TITLE
How to use with a session store

### ISSUE THREAD

**Issue by erewok** [haskell-servant/servant-auth#132]
Hi all,

I've been using this library on one of my personal projects where I was experimenting with running a handful of docker containers. I noticed that when I ran three instances of my application, my session would sometimes show me as logged-out, but if I just refreshed the browser, I'd be logged in again. When I went back to a single container, this problem went away. 

I did not do extensive debugging on this, but it occurred to me that in the past I've typically used memcached or redis to store sessions for applications, and these sessions are reachable by any instance of the application. Is it possible to do this with `servant-auth-server` or are there plans to support caching sessions in a data store? 

Thanks.

**Comment by domenkozar** [comment]
Do you share the key you pass into `defaultJWTSettings :: JWK -> JWTSettings` between those instances?

Which auth type are you using? :)

**Comment by erewok** [comment]
I did not share the key and realized after the fact that that would most likely be my issue. I suppose that I could first generate the key and pass it into the app as an environment variable.

This may be something worth  mentioning in a tutorial?

I was using Cookie auth.

**Comment by domenkozar** [comment]
Added to #129 list, thanks.
