### ISSUE TITLE
Move FromJWT/ToJWT to servant-auth

### ISSUE THREAD

**Issue by domenkozar** [haskell-servant/servant-auth#135]
So that an api package using the two typeclasses doesn't have to depend on servant-auth-server 

https://github.com/haskell-servant/servant-auth/blob/6b8056fc19c0338f3e858d46c5307f0fd0ac59ea/servant-auth-server/src/Servant/Auth/Server/Internal/JWT.hs#L22-L44

**Comment by reygoch** [comment]
I was just about to open an issue for this. I'm using GHCJS and can't compile a program which depends on `To/FromJWT` classes because `servant-auth-server` brings a whole `network` package and his friends which don't compile on GHCJS.
