### ISSUE TITLE
HasLink instance not released to Hackage

### ISSUE THREAD

**Issue by cdepillabout** [haskell-servant/servant-auth#147]
It appears that a `HasLink` instance for `Auth` has been added to the `servant-auth` package (in #105?) back in July 2018, but it hasn't actually been released to Hackage.

Hackage is down right now, so I can't link to it, but looking on Stackage, the current version of `servant-auth` is 0.3.2.0, and it doesn't appear to have the `HasLink` instance for `Auth`:

https://www.stackage.org/haddock/lts-13.15/servant-auth-0.3.2.0/src/Servant.Auth.html

It would be great to get a release of `servant-auth` with this instance defined.

**Comment by domenkozar** [comment]
This was fixed a long time ago.
