### ISSUE TITLE
Base 4.14.0.0

### ISSUE THREAD

**Issue by ldgrp** [haskell-servant/servant-auth#176]
The current [base](https://hackage.haskell.org/package/base) is 4.14.0.0

According to [hackage](https://hackage.haskell.org/package/servant-auth), servant-auth 0.3.2.0 only supports base (>=4.8 && <4.14) but the [cabal files](https://github.com/haskell-servant/servant-auth/blob/master/servant-auth/servant-auth.cabal) say otherwise.

**Comment by domenkozar** [comment]
I'll make a release next week.

**Comment by gwils** [comment]
It looks like this has made it to hackage as servant-auth 0.4
Can we please get a release for servant-auth-server to update to servant-auth 0.4 and base 4.14?

**Comment by domenkozar** [comment]
While releasing yesterday I had to suddenly take care of personal life.

I'm going to release the rest now.

**Comment by gwils** [comment]
Thanks!
