### ISSUE TITLE
Getting started example

### ISSUE THREAD

**Issue by wpoosanguansit** [haskell-servant/servant-auth#18]
Hi, I am new to servant and, implicitly, servant-auth.  I managed to get the code running in my local instance.  However, I am still not clear on how to use the code to protect resources.  Would it be possible to provide a more complete example - having user creating accounts or token + defining protected/unprotected endpoints?  I do see in the current example code calling

localhost:7249/name -v

However, I still do not see where that is defined, i.e.  Thanks for your help.

**Comment by wpoosanguansit** [comment]
In between, per the doc the key is usually persisted.  I tried

let k = toJSON (myKey :: Jose.JWK)

which does turn the key to JSON successfully.  However, I do get compile error when I tried to read that JSON back into Jose.JWK.  How do I turn the JSON into a proper Jose.JWK for reuse?  Thanks for your help.

**Comment by wpoosanguansit** [comment]
I am looking to invoke "login" end point for the login and getting:

Only GET or HEAD is supported%

command is:

curl -H "Content-Type: application/json" -X POST -d '{"username":"xyz","password":"xyz"}' http://localhost:7249/login

How do we login given the sample code?  Thanks for your help.

**Comment by 3noch** [comment]
I think the README is missing an example of a POST to the `/login` endpoint.

**Comment by wpoosanguansit** [comment]
Thank you for your help.  I also found that :<|> serveDirectory "example/static" was moved to last in the route as well. (it was the first argument before).  Now I have got it working.  Thanks again.

**Comment by domenkozar** [comment]
There is also http://haskell-servant.readthedocs.io/en/stable/cookbook/jwt-and-basic-auth/JWTAndBasicAuth.html

**Comment by domenkozar** [comment]
Don't think there's much to do here :)
