### ISSUE TITLE
support writing custom combinators for authorization

### ISSUE THREAD

**Issue by soenkehahn** [haskell-servant/servant-auth#5]
The given `Auth` combinator takes care of authentication. It would be nice if `servant-auth` (or `servant`) allowed to easily write a custom combinator `MyAuth` that used `servant-auth-server` for authentication, but then also took care of authorization, where

``` haskell
Server (MyAuth :> api) ~ MyUser -> Server api
```

The `HasServer` instance would yield `401`s for missing or invalid authentication and `403` for insufficient privileges.

**Comment by sordina** [comment]
Yes this would be a great way to not have to littler authz code throughout routes. Even simple things like expiring tokens.

**Comment by domenkozar** [comment]
Closing as duplicate of #73 (as it has more info)
