### ISSUE TITLE
cookie authentication without csrf

### ISSUE THREAD

**Issue by cdepillabout** [haskell-servant/servant-auth#51]
I'd like to protect a route that returns an HTML page with cookie authentication.

Based on the example from the README, I'd want my routes to look something like this:

```haskell
type Protected
   = "name" :> Get '[JSON] String
 :<|> "email" :> Get '[JSON] String
 :<|> Raw

type Unprotected =
 "login"
     :> ReqBody '[JSON] Login
     :> PostNoContent
            '[JSON]
            (Headers
              '[ Header "Set-Cookie" SetCookie
               , Header "Set-Cookie" SetCookie
               ]
              NoContent)

type API = Unprotected :<|> (Auth '[Cookie] User :> Protected)
```

If I'm using [`Cookie`](https://github.com/plow-technologies/servant-auth/blob/a74cc320b43e791d941a3ed54d5fb29ac1e16511/servant-auth/src/Servant/Auth.hs#L25) authentiation, the problem with this is that the `Raw` routes in `Protected` will [require](https://github.com/plow-technologies/servant-auth/blob/a74cc320b43e791d941a3ed54d5fb29ac1e16511/servant-auth-server/src/Servant/Auth/Server/Internal/Cookie.hs#L32) that the `X-XSRF-TOKEN` header is set.  If a user is accessing a page in their browser and clicks a link, I don't think that the `X-XSRF-TOKEN` will be set.  (Maybe it would be possible to do this somehow with Javascript, but I'd rather not have to take that approach.)

It would be nice to have a separate authentication like `CookieNoCSRF` that doesn't check the `X-XSRF-TOKEN` header.  Is there a way to do this currently?  Or would it require an additional authentication method?  Or maybe there is a better way?

**Comment by 3noch** [comment]
@cdepillabout Take a look at my PR #54. It allows you to disable XSRF and use other checks instead (if desired).

**Comment by cdepillabout** [comment]
#54 looks like it would work for my use-case.  I would just be able to completely disable XSRF.

Actually, I've moved to just using [servant-auth-cookie](https://hackage.haskell.org/package/servant-auth-cookie).  I don't think it does any sort of xsrf protection, but it does seem to work for simple cookie authentication.

If your PR gets merged, it looks like I would be able to use servant-auth as well.

**Comment by harendra-kumar** [comment]
It seems CSRF in servant protects GET requests as well which I think is unnecessary, unless I am missing something. If we just fix that then GET requests will just work and for POST or other state modifying operations one can afford to use javascript to set the token.

**Comment by domenkozar** [comment]
https://github.com/haskell-servant/servant-auth/pull/92 made XSRF optional.
