### ISSUE TITLE
GHC-8.2 support

### ISSUE THREAD

**Issue by phadej** [haskell-servant/servant-auth#52]
blocked on https://github.com/frasertweedale/hs-jose/issues/51

**Comment by phadej** [comment]
Also https://github.com/sol/hpack/issues/188 is an inconvenience.

**Comment by rikvdkleij** [comment]
frasertweedale/hs-jose#51 is closed. Can new version be released which supports GHC 8.2.1? Do you need help?

**Comment by phadej** [comment]
`master` is 8.2 ready.
