### ISSUE TITLE
Orphans for SetCookie break derived clients

### ISSUE THREAD

**Issue by 3noch** [haskell-servant/servant-auth#58]
Since the `ToHttpApiData` instances for `SetCookie` are only available as orphans in `servant-auth-server`, clients that use the *same API type* will not be able to derive client functions because these instances will be missing. These instances need to be pulled out into a different library or included in `servant-auth` itself.

**Comment by 3noch** [comment]
As a stop gap, the client can define *its own orphans* (not a pleasant option). It's also possible to parameterize the API type in such a way that these headers types only appear for the server and are removed for the client.

```haskell
type Unprotected sessionHeaders = "login" :> ReqBody '[JSON] Login :> Post '[JSON] (sessionHeaeders $ User)

type family ($) (f :: k1) (x :: k2) = k3

-- Client side
data Id
type instance Id $ x = x

type Api = Unprotected Id

-- Server side
data SessionHeaders
type instance SessionHeaders $ x = Headers '[ Header "Set-Cookie" SetCookie, Header "Set-Cookie" SetCookie ] x
```

**Comment by jkarni** [comment]
I think the solution is just wrapping `Cookie` into a newtype so that the instances isn't orphan. The current situation arose from the assumption that the `cookie` library would eventually adopt the instance. Which after discussion it became clear that it - sensibly - wouldn't.

**Comment by domenkozar** [comment]
Would newtype be considered a breaking change, given that instances for newtyped Cookie wouldn't affect cookie library?

**Comment by domenkozar** [comment]
The orphan instances are now in https://github.com/fizruk/http-api-data/pull/74/files and servant-auth master reflects that.
