### ISSUE TITLE
Update to jose 6

### ISSUE THREAD

**Issue by 3noch** [haskell-servant/servant-auth#59]
Jose 6 is out and is now in LTS. Some changes will be necessary.

**Comment by mbeidler** [comment]
I was experimenting with changes that require `jose-0.6`, so I thought I'd go ahead and make the changes in **servant-auth**.

In Jose 6, the only way to obtain the `ClaimsSet` is in the `IO` monad (via the [Jose.verifyClaims](https://hackage.haskell.org/package/jose-0.6.0.3/docs/Crypto-JWT.html#v:verifyClaims) function, previously `ClaimsSet` was a field on `JWT`). Given that this is the case, I was curious what the desired approach would be.

One option would be to simply change the signature from:
```haskell
class FromJWT a where
  decodeJWT :: Jose.JWT -> Either T.Text a

-- to (name could be changed or left as `FromJWT`)
class FromJWTClaimsSet a where
  decodeJWTClaimsSet :: Jose.ClaimsSet -> Either T.Text a
```

We'd also make the analogous change in signature for `ToJWT`. If that's acceptable or not, or if you'd rather I just pushed a PR and you can review, let me know.

**Comment by 3noch** [comment]
@mchaver @jkarni ?

**Comment by mchaver** [comment]
@3noch @mbeidler 

I think the ideal solution would be something like this to maintain backwards compatibility.

```haskell
#if MIN_VERSION_jose(0,6,0)
class FromJWT a where
  decodeJWT :: Jose.ClaimsSet -> Either T.Text a
#else
class FromJWT a where
  decodeJWT :: Jose.JWT -> Either T.Text a
#endif
```

**Comment by phadej** [comment]
I don't see a reason to keep `jose-0.5` around, based on https://matrix.hackage.haskell.org/package/jose the supported GHC are the same, so there aren't hard obstacles to upgrade.

**Comment by mbeidler** [comment]
I went ahead and put a PR up with what I had. If the consensus is that I should support previous Jose versions, I can add the pragmas. @mchaver @phadej

**Comment by mchaver** [comment]
@mbeidler based on what @phadej mentioned, I think it should be fine.
