### ISSUE TITLE
Support servant-auth-0.3.*

### ISSUE THREAD

**Issue by basvandijk** [haskell-servant/servant-auth#62]
I'm trying to build `servant-auth-server` via nixpkgs.

```
$ nix-build -A haskellPackages.servant-auth-server
...
cabal: Encountered missing dependencies:
jose ==0.5.*, servant-auth ==0.2.*
```

The build environment has `jose-0.6.0.3` and `servant-auth-0.3.0.0`. I see there's already a [PR for upgrading to jose-0.6](https://github.com/plow-technologies/servant-auth/pull/61). 

It would be great if `servant-auth-server` could support `servant-auth-0.3.*`.

**Comment by phadej** [comment]
I wonder what is `servant-auth-0.3`, as there are no trails in the repository. Ping @jkarni

**Comment by basvandijk** [comment]
I have the same question. There's clearly a [servant-auth-0.3.0.0](http://hackage.haskell.org/package/servant-auth-0.3.0.0) on Hackage so maybe a tag wasn't pushed or something.

**Comment by jkarni** [comment]
Pushed the tags. Sorry about that!

**Comment by domenkozar** [comment]
Shouldn't this be closed as fixed? :)
