### ISSUE TITLE
Syntax highlighting in README

### ISSUE THREAD

**Issue by danbroooks** [haskell-servant/servant-auth#72]
I was going to submit a PR to turn on syntax highlighting for the examples in the readme, but it looks like the examples are already marked up for highlighting, just not using github flavoured markdown. Briefly looking online I couldn't find anywhere that this readme was rendered other than here (hackage points users here for viewing the readme).

Is this a throwback to when this readme would be displayed elsewhere, and it can just be updated to use GFM now?

**Comment by alpmestan** [comment]
I think it's safe to say that this README can be changed to use GFM without it breaking anything.

**Comment by danbroooks** [comment]
Looks like this is being taken care of in https://github.com/haskell-servant/servant-auth/pull/44

**Comment by domenkozar** [comment]
Also #90
