### ISSUE TITLE
Servant.Auth.Servant.IsSecure vs Servant.API.IsSecure.IsSecure

### ISSUE THREAD

**Issue by dbaynard** [haskell-servant/servant-auth#91]
Would it be possible to re-use the type from [servant](https://hackage.haskell.org/package/servant-0.13.0.1/docs/Servant-API-IsSecure.html#t:IsSecure) rather than implement the new one in Servant.Auth.Server.Internal.ConfigTypes, here? Happy to PR if desired.

Each is defined independently as 

```haskell
data IsSecure
  = Secure
  | NotSecure
```

and the only difference is the `HasLink` instance for the `servant` variant.

**Comment by alpmestan** [comment]
That would indeed be nice! I don't know why this got duplicated.

**Comment by domenkozar** [comment]
And there is also https://hackage.haskell.org/package/servant-client-core-0.13.0.1/docs/Servant-Client-Core-Internal-BaseUrl.html#t:Scheme

**Comment by domenkozar** [comment]
Addressed in https://github.com/haskell-servant/servant-auth/pull/102
